"""Generates setup notebooks for creating Databricks resources needed by translated jobs."""

from __future__ import annotations

import textwrap

from orchestra.models.dab import DabNotebook, SecretInstruction, SetupTask


def generate_setup_tasks(
    secrets: list[SecretInstruction],
    setup_tasks: list[SetupTask],
    catalog: str,
    schema: str,
) -> list[DabNotebook]:
    """Generates setup notebooks for provisioning required Databricks resources.

    Args:
        secrets: Secret instructions collected from all prepared activities.
        setup_tasks: Additional setup tasks (volume creation, connections, etc.).
        catalog: Target Unity Catalog name.
        schema: Target schema name within the catalog.

    Returns:
        List of DabNotebook objects for the setup notebooks.
    """
    notebooks: list[DabNotebook] = []

    if secrets:
        notebook = _generate_secrets_setup_notebook(secrets)
        notebooks.append(notebook)

    volume_tasks = [t for t in setup_tasks if t.type == "volume"]
    if volume_tasks:
        notebook = _generate_volume_setup_notebook(volume_tasks, catalog, schema)
        notebooks.append(notebook)

    connection_tasks = [t for t in setup_tasks if t.type == "connection"]
    if connection_tasks:
        notebook = _generate_connection_setup_notebook(connection_tasks, catalog)
        notebooks.append(notebook)

    return notebooks


def _generate_secrets_setup_notebook(secrets: list[SecretInstruction]) -> DabNotebook:
    """Generates a notebook that creates secret scopes and populates secrets.

    Args:
        secrets: Secret instructions to provision.

    Returns:
        A DabNotebook for the secrets setup notebook.
    """
    header = textwrap.dedent("""\
        # Databricks notebook source
        # MAGIC %md
        # MAGIC # Setup: Create Secret Scopes and Secrets
        # MAGIC
        # MAGIC *Auto-generated by Orchestra. Run this notebook once before deploying the job.*
        # MAGIC
        # MAGIC This notebook creates the Databricks secret scopes and placeholder secrets
        # MAGIC required by the translated pipelines.  After running, update each secret
        # MAGIC with the real credential value using the Databricks CLI:
        # MAGIC
        # MAGIC ```bash
        # MAGIC databricks secrets put-secret <scope> <key>
        # MAGIC ```
    """)

    separator = "\n# COMMAND ----------\n\n"

    scopes: dict[str, list[SecretInstruction]] = {}
    for s in secrets:
        scopes.setdefault(s.scope, []).append(s)

    body_parts: list[str] = []
    for scope_name, scope_secrets in sorted(scopes.items()):
        lines: list[str] = [f"# Create scope: {scope_name}"]
        lines.append("try:")
        lines.append(f'    dbutils.secrets.createScope(scope="{scope_name}")')
        lines.append(f'    print("Created scope: {scope_name}")')
        lines.append("except Exception as e:")
        lines.append('    if "RESOURCE_ALREADY_EXISTS" in str(e):')
        lines.append(f'        print("Scope already exists: {scope_name}")')
        lines.append("    else:")
        lines.append("        raise")
        lines.append("")

        for secret in scope_secrets:
            lines.append(f"# {secret.value_source}")
            lines.append(f'dbutils.secrets.put(scope="{scope_name}", key="{secret.key}", string_value="PLACEHOLDER")')
            lines.append(f'print("Created secret: {scope_name}/{secret.key}")')
            lines.append("")

        body_parts.append("\n".join(lines))

    body = separator.join(body_parts)

    summary = separator + "# MAGIC %md\n"
    summary += "# MAGIC ## Next Steps\n"
    summary += "# MAGIC\n"
    summary += f"# MAGIC Created **{len(scopes)}** scope(s) and **{len(secrets)}** secret(s).\n"
    summary += "# MAGIC\n"
    summary += "# MAGIC Replace each PLACEHOLDER value with the real credential:\n"
    summary += "# MAGIC ```bash\n"
    for scope_name, scope_secrets in sorted(scopes.items()):
        for secret in scope_secrets:
            summary += f"# MAGIC databricks secrets put-secret {scope_name} {secret.key}\n"
    summary += "# MAGIC ```\n"

    content = header + separator + body + summary
    return DabNotebook(
        relative_path="setup/create_secrets.py",
        content=content,
    )


def _generate_volume_setup_notebook(
    volume_tasks: list[SetupTask],
    catalog: str,
    schema: str,
) -> DabNotebook:
    """Generates a notebook that creates Unity Catalog volumes.

    Args:
        volume_tasks: Volume creation setup tasks.  Each task's ``config``
            carries ``volume_name``, ``volume_type`` (``MANAGED`` /
            ``EXTERNAL``), ``location`` (``abfss://`` / ``s3://`` /
            ``gs://`` URL), ``location_type`` (ADF dataset location type),
            and optional ``storage_account``.
        catalog: Target Unity Catalog name.
        schema: Target schema name.

    Returns:
        A DabNotebook for the volume setup notebook.
    """
    header = textwrap.dedent("""\
        # Databricks notebook source
        # MAGIC %md
        # MAGIC # Setup: Create Unity Catalog Volumes
        # MAGIC
        # MAGIC *Auto-generated by Orchestra. Run this notebook once before deploying the job.*
        # MAGIC
        # MAGIC For each external volume below, this notebook attempts to create the
        # MAGIC underlying Storage Credential and External Location first.  Both require
        # MAGIC `CREATE STORAGE CREDENTIAL` / `CREATE EXTERNAL LOCATION` privileges and
        # MAGIC the appropriate cloud-side configuration:
        # MAGIC
        # MAGIC - **Azure** — an Access Connector for Azure Databricks with
        # MAGIC   Storage Blob Data Contributor on the storage account.
        # MAGIC - **AWS** — an IAM role with read/write on the bucket trusted by the
        # MAGIC   Databricks IAM principal.
        # MAGIC - **GCP** — a service account with `roles/storage.admin` (or finer)
        # MAGIC   on the bucket.
        # MAGIC
        # MAGIC Replace the `PLACEHOLDER` values in the credential cells before running.
    """)

    separator = "\n# COMMAND ----------\n\n"

    # Group external-location and credential creation by URL so we don't
    # emit duplicate DDL when several sinks share a container.
    seen_locations: set[str] = set()
    seen_credentials: set[str] = set()

    body_parts: list[str] = []
    for task in volume_tasks:
        config = task.config
        volume_name = config.get("volume_name", "unknown")
        volume_type = (config.get("volume_type") or "MANAGED").upper()
        location = config.get("location", "")
        location_type = config.get("location_type", "") or ""

        fqn = f"{catalog}.{schema}.{volume_name}"
        lines: list[str] = [f"# Create volume: {volume_name}"]

        if volume_type == "EXTERNAL" and location:
            credential_name = _credential_name_for(volume_name)
            external_location_name = _external_location_name_for(volume_name)

            if credential_name not in seen_credentials:
                seen_credentials.add(credential_name)
                lines.append(_render_storage_credential_ddl(credential_name, location_type))

            if location not in seen_locations:
                seen_locations.add(location)
                lines.append(_render_external_location_ddl(external_location_name, location, credential_name))

            lines.append(f"spark.sql(\"CREATE EXTERNAL VOLUME IF NOT EXISTS {fqn} LOCATION '{location}'\")")
        else:
            lines.append(f'spark.sql("CREATE VOLUME IF NOT EXISTS {fqn}")')

        lines.append(f'print("Created volume: {fqn}")')
        body_parts.append("\n".join(lines))

    content = header + separator + separator.join(body_parts) + "\n"
    return DabNotebook(
        relative_path="setup/create_volumes.py",
        content=content,
    )


def _credential_name_for(volume_name: str) -> str:
    return f"orchestra_{volume_name}_credential"


def _external_location_name_for(volume_name: str) -> str:
    return f"orchestra_{volume_name}_location"


def _render_storage_credential_ddl(credential_name: str, location_type: str) -> str:
    """Emits a CREATE STORAGE CREDENTIAL block keyed off the source cloud."""
    if location_type in ("AzureBlobStorageLocation", "AzureBlobFSLocation"):
        return (
            "# Azure: requires an Access Connector for Azure Databricks granted\n"
            "# Storage Blob Data Contributor on the target account.\n"
            'spark.sql("""\n'
            f"  CREATE STORAGE CREDENTIAL IF NOT EXISTS {credential_name}\n"
            "  WITH AZURE_MANAGED_IDENTITY (\n"
            "    'PLACEHOLDER_ACCESS_CONNECTOR_RESOURCE_ID'\n"
            "  )\n"
            f"  COMMENT 'Auto-generated by Orchestra for volume {credential_name}'\n"
            '""")'
        )
    if location_type == "AmazonS3Location":
        return (
            "# AWS: requires an IAM role trusted by the Databricks principal.\n"
            'spark.sql("""\n'
            f"  CREATE STORAGE CREDENTIAL IF NOT EXISTS {credential_name}\n"
            "  WITH IAM_ROLE 'arn:aws:iam::PLACEHOLDER_ACCOUNT_ID:role/PLACEHOLDER_ROLE'\n"
            f"  COMMENT 'Auto-generated by Orchestra for volume {credential_name}'\n"
            '""")'
        )
    if location_type == "GoogleCloudStorageLocation":
        return (
            "# GCP: requires a Databricks service account email.\n"
            'spark.sql("""\n'
            f"  CREATE STORAGE CREDENTIAL IF NOT EXISTS {credential_name}\n"
            "  WITH GCP_SERVICE_ACCOUNT 'PLACEHOLDER_SERVICE_ACCOUNT_EMAIL'\n"
            f"  COMMENT 'Auto-generated by Orchestra for volume {credential_name}'\n"
            '""")'
        )
    return (
        f"# Storage credential for {credential_name} could not be auto-typed (unknown\n"
        f"# location_type={location_type!r}).  Create it manually before this cell.\n"
        f"# See https://docs.databricks.com/aws/en/connect/unity-catalog/storage-credentials"
    )


def _render_external_location_ddl(name: str, url: str, credential: str) -> str:
    return (
        'spark.sql("""\n'
        f"  CREATE EXTERNAL LOCATION IF NOT EXISTS {name}\n"
        f"  URL '{url}'\n"
        f"  WITH (STORAGE CREDENTIAL {credential})\n"
        f"  COMMENT 'Auto-generated by Orchestra'\n"
        '""")'
    )


def _generate_connection_setup_notebook(
    connection_tasks: list[SetupTask],
    catalog: str,
) -> DabNotebook:
    """Generates a notebook that creates external connections.

    Args:
        connection_tasks: Connection creation setup tasks.
        catalog: Target Unity Catalog name.

    Returns:
        A DabNotebook for the connection setup notebook.
    """
    header = textwrap.dedent("""\
        # Databricks notebook source
        # MAGIC %md
        # MAGIC # Setup: Create External Connections
        # MAGIC
        # MAGIC *Auto-generated by Orchestra. Run this notebook once before deploying the job.*
        # MAGIC
        # MAGIC Update the placeholder connection details below with real values before running.
    """)

    separator = "\n# COMMAND ----------\n\n"

    body_parts: list[str] = []
    for task in connection_tasks:
        config = task.config
        conn_name = config.get("connection_name", "unknown")
        conn_type = config.get("connection_type", "MYSQL")
        host = config.get("host", "PLACEHOLDER_HOST")
        port = config.get("port", "3306")

        lines: list[str] = [f"# Create connection: {conn_name}"]
        lines.append('spark.sql("""')
        lines.append(f"    CREATE CONNECTION IF NOT EXISTS {conn_name}")
        lines.append(f"    TYPE {conn_type}")
        lines.append(f"    OPTIONS (host '{host}', port '{port}')")
        lines.append('""")')
        lines.append(f'print("Created connection: {conn_name}")')
        body_parts.append("\n".join(lines))

    content = header + separator + separator.join(body_parts) + "\n"
    return DabNotebook(
        relative_path="setup/create_connections.py",
        content=content,
    )
