"""Generate setup notebooks for creating Databricks resources needed by translated jobs.

Setup notebooks handle one-time provisioning of:
- Secret scopes and secrets
- Unity Catalog volumes
- External connection configuration
"""

from __future__ import annotations

import textwrap

from orchestra.models.dab import DabNotebook, SecretInstruction, SetupTask


def generate_setup_tasks(
    secrets: list[SecretInstruction],
    setup_tasks: list[SetupTask],
    catalog: str,
    schema: str,
) -> list[DabNotebook]:
    """Generate setup notebooks for provisioning required Databricks resources.

    Args:
        secrets: Secret instructions collected from all prepared activities.
        setup_tasks: Additional setup tasks (volume creation, connections, etc.).
        catalog: Target Unity Catalog name.
        schema: Target schema name within the catalog.

    Returns:
        List of DabNotebook objects for the setup notebooks.
    """
    notebooks: list[DabNotebook] = []

    if secrets:
        nb = _generate_secrets_setup_notebook(secrets)
        notebooks.append(nb)

    volume_tasks = [t for t in setup_tasks if t.type == "volume"]
    if volume_tasks:
        nb = _generate_volume_setup_notebook(volume_tasks, catalog, schema)
        notebooks.append(nb)

    connection_tasks = [t for t in setup_tasks if t.type == "connection"]
    if connection_tasks:
        nb = _generate_connection_setup_notebook(connection_tasks, catalog)
        notebooks.append(nb)

    return notebooks


def _generate_secrets_setup_notebook(secrets: list[SecretInstruction]) -> DabNotebook:
    """Generate a notebook that creates secret scopes and populates secrets.

    Args:
        secrets: Secret instructions to provision.

    Returns:
        A DabNotebook for the secrets setup notebook.
    """
    header = textwrap.dedent("""\
        # Databricks notebook source
        # MAGIC %md
        # MAGIC # Setup: Create Secret Scopes and Secrets
        # MAGIC
        # MAGIC *Auto-generated by Orchestra. Run this notebook once before deploying the job.*
        # MAGIC
        # MAGIC This notebook creates the Databricks secret scopes and placeholder secrets
        # MAGIC required by the translated pipelines.  After running, update each secret
        # MAGIC with the real credential value using the Databricks CLI:
        # MAGIC
        # MAGIC ```bash
        # MAGIC databricks secrets put-secret <scope> <key>
        # MAGIC ```
    """)

    separator = "\n# COMMAND ----------\n\n"

    # Group secrets by scope
    scopes: dict[str, list[SecretInstruction]] = {}
    for s in secrets:
        scopes.setdefault(s.scope, []).append(s)

    body_parts: list[str] = []
    for scope_name, scope_secrets in sorted(scopes.items()):
        lines: list[str] = [f"# Create scope: {scope_name}"]
        lines.append("try:")
        lines.append(f'    dbutils.secrets.createScope(scope="{scope_name}")')
        lines.append(f'    print("Created scope: {scope_name}")')
        lines.append("except Exception as e:")
        lines.append('    if "RESOURCE_ALREADY_EXISTS" in str(e):')
        lines.append(f'        print("Scope already exists: {scope_name}")')
        lines.append("    else:")
        lines.append("        raise")
        lines.append("")

        for secret in scope_secrets:
            lines.append(f"# {secret.value_source}")
            lines.append(f'dbutils.secrets.put(scope="{scope_name}", key="{secret.key}", string_value="PLACEHOLDER")')
            lines.append(f'print("Created secret: {scope_name}/{secret.key}")')
            lines.append("")

        body_parts.append("\n".join(lines))

    body = separator.join(body_parts)

    # Summary cell
    summary = separator + "# MAGIC %md\n"
    summary += "# MAGIC ## Next Steps\n"
    summary += "# MAGIC\n"
    summary += f"# MAGIC Created **{len(scopes)}** scope(s) and **{len(secrets)}** secret(s).\n"
    summary += "# MAGIC\n"
    summary += "# MAGIC Replace each PLACEHOLDER value with the real credential:\n"
    summary += "# MAGIC ```bash\n"
    for scope_name, scope_secrets in sorted(scopes.items()):
        for secret in scope_secrets:
            summary += f"# MAGIC databricks secrets put-secret {scope_name} {secret.key}\n"
    summary += "# MAGIC ```\n"

    content = header + separator + body + summary
    return DabNotebook(
        relative_path="setup/create_secrets.py",
        content=content,
    )


def _generate_volume_setup_notebook(
    volume_tasks: list[SetupTask],
    catalog: str,
    schema: str,
) -> DabNotebook:
    """Generate a notebook that creates Unity Catalog volumes.

    Args:
        volume_tasks: Volume creation setup tasks.
        catalog: Target Unity Catalog name.
        schema: Target schema name.

    Returns:
        A DabNotebook for the volume setup notebook.
    """
    header = textwrap.dedent("""\
        # Databricks notebook source
        # MAGIC %md
        # MAGIC # Setup: Create Unity Catalog Volumes
        # MAGIC
        # MAGIC *Auto-generated by Orchestra. Run this notebook once before deploying the job.*
    """)

    separator = "\n# COMMAND ----------\n\n"

    body_parts: list[str] = []
    for task in volume_tasks:
        config = task.config
        volume_name = config.get("volume_name", "unknown")
        volume_type = config.get("volume_type", "MANAGED")
        location = config.get("location", "")

        lines: list[str] = [f"# Create volume: {volume_name}"]
        fqn = f"{catalog}.{schema}.{volume_name}"
        if volume_type.upper() == "EXTERNAL" and location:
            lines.append(f"spark.sql(\"CREATE EXTERNAL VOLUME IF NOT EXISTS {fqn} LOCATION '{location}'\")")
        else:
            lines.append(f'spark.sql("CREATE VOLUME IF NOT EXISTS {fqn}")')
        lines.append(f'print("Created volume: {fqn}")')
        body_parts.append("\n".join(lines))

    content = header + separator + separator.join(body_parts) + "\n"
    return DabNotebook(
        relative_path="setup/create_volumes.py",
        content=content,
    )


def _generate_connection_setup_notebook(
    connection_tasks: list[SetupTask],
    catalog: str,
) -> DabNotebook:
    """Generate a notebook that creates external connections.

    Args:
        connection_tasks: Connection creation setup tasks.
        catalog: Target Unity Catalog name.

    Returns:
        A DabNotebook for the connection setup notebook.
    """
    header = textwrap.dedent("""\
        # Databricks notebook source
        # MAGIC %md
        # MAGIC # Setup: Create External Connections
        # MAGIC
        # MAGIC *Auto-generated by Orchestra. Run this notebook once before deploying the job.*
        # MAGIC
        # MAGIC Update the placeholder connection details below with real values before running.
    """)

    separator = "\n# COMMAND ----------\n\n"

    body_parts: list[str] = []
    for task in connection_tasks:
        config = task.config
        conn_name = config.get("connection_name", "unknown")
        conn_type = config.get("connection_type", "MYSQL")
        host = config.get("host", "PLACEHOLDER_HOST")
        port = config.get("port", "3306")

        lines: list[str] = [f"# Create connection: {conn_name}"]
        lines.append('spark.sql("""')
        lines.append(f"    CREATE CONNECTION IF NOT EXISTS {conn_name}")
        lines.append(f"    TYPE {conn_type}")
        lines.append(f"    OPTIONS (host '{host}', port '{port}')")
        lines.append('""")')
        lines.append(f'print("Created connection: {conn_name}")')
        body_parts.append("\n".join(lines))

    content = header + separator + separator.join(body_parts) + "\n"
    return DabNotebook(
        relative_path="setup/create_connections.py",
        content=content,
    )
