"""Generate Python notebook content for activities that need custom notebooks.

Each generator produces a self-contained Databricks notebook with:
- A ``# Databricks notebook source`` header
- Imports for required modules
- ``dbutils.widgets.get()`` for runtime parameters
- ``dbutils.secrets.get()`` for credentials
- ``dbutils.notebook.exit()`` to return results
"""

from __future__ import annotations

import json
import textwrap
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from orchestra.models.ir import (
        CopyActivity,
        DeleteActivity,
        LookupActivity,
        SetVariableActivity,
        WebActivity,
    )


def _notebook_header(title: str) -> str:
    """Return the standard Databricks notebook header block."""
    return textwrap.dedent(f"""\
        # Databricks notebook source
        # MAGIC %md
        # MAGIC # {title}
        # MAGIC
        # MAGIC *Auto-generated by Orchestra. Do not edit manually unless necessary.*
    """)


def _command_separator() -> str:
    """Return the Databricks cell separator comment."""
    return "\n# COMMAND ----------\n\n"


# ---------------------------------------------------------------------------
# Lookup notebook
# ---------------------------------------------------------------------------

_DB_SOURCE_TYPES = {
    "AzureSqlSource",
    "SqlServerSource",
    "OracleSource",
    "PostgreSqlSource",
    "MySqlSource",
    "SqlSource",
    "CosmosDbSqlApiSource",
    "SqlDWSource",
}


def generate_lookup_notebook(activity: LookupActivity) -> str:
    """Generate a Python notebook that executes a lookup query.

    Args:
        activity: The LookupActivity IR node.

    Returns:
        Complete notebook source code as a string.
    """
    header = _notebook_header(f"Lookup: {activity.name}")
    source_type = activity.source_type or ""
    query = activity.source_query or ""

    if source_type in _DB_SOURCE_TYPES:
        scope = f"orchestra-{activity.task_key}"
        body = textwrap.dedent(f"""\
            import json

            # Parameters
            first_row_only = dbutils.widgets.get("first_row_only") == "true"

            # Credentials
            jdbc_url = dbutils.secrets.get(scope="{scope}", key="jdbc-url")
            jdbc_password = dbutils.secrets.get(scope="{scope}", key="jdbc-password")
            jdbc_user = dbutils.secrets.get(scope="{scope}", key="jdbc-user")

            # Execute lookup query
            query = \"\"\"{query}\"\"\"

            df = (
                spark.read.format("jdbc")
                .option("url", jdbc_url)
                .option("user", jdbc_user)
                .option("password", jdbc_password)
                .option("query", query)
                .load()
            )

            if first_row_only:
                result = df.first()
                output = json.dumps(result.asDict() if result else {{}})
            else:
                rows = [row.asDict() for row in df.collect()]
                output = json.dumps(rows)

            dbutils.notebook.exit(output)
        """)
    else:
        body = textwrap.dedent(f"""\
            import json

            # Parameters
            first_row_only = dbutils.widgets.get("first_row_only") == "true"

            # Execute lookup query via Spark SQL
            query = \"\"\"{query}\"\"\"
            df = spark.sql(query)

            if first_row_only:
                result = df.first()
                output = json.dumps(result.asDict() if result else {{}})
            else:
                rows = [row.asDict() for row in df.collect()]
                output = json.dumps(rows)

            dbutils.notebook.exit(output)
        """)

    return header + _command_separator() + body


# ---------------------------------------------------------------------------
# Web activity notebook
# ---------------------------------------------------------------------------


def generate_web_activity_notebook(activity: WebActivity) -> str:
    """Generate a Python notebook that makes an HTTP request.

    Args:
        activity: The WebActivity IR node.

    Returns:
        Complete notebook source code as a string.
    """
    header = _notebook_header(f"Web Activity: {activity.name}")

    headers_literal = json.dumps(activity.headers) if activity.headers else "{}"

    auth_block = ""
    auth = activity.authentication
    if auth:
        scope = f"orchestra-{activity.task_key}"
        auth_type = auth.get("type", "")
        if auth_type in ("ServicePrincipal", "MSI", "ManagedServiceIdentity"):
            auth_block = textwrap.dedent(f"""\
                # Authentication ({auth_type})
                auth_token = dbutils.secrets.get(scope="{scope}", key="auth-credential")
                headers["Authorization"] = f"Bearer {{auth_token}}"
            """)
        elif auth_type == "Basic":
            auth_block = textwrap.dedent(f"""\
                # Authentication (Basic)
                import base64
                username = dbutils.secrets.get(scope="{scope}", key="auth-username")
                password = dbutils.secrets.get(scope="{scope}", key="auth-credential")
                token = base64.b64encode(f"{{username}}:{{password}}".encode()).decode()
                headers["Authorization"] = f"Basic {{token}}"
            """)
        else:
            auth_block = textwrap.dedent(f"""\
                # Authentication
                auth_credential = dbutils.secrets.get(scope="{scope}", key="auth-credential")
                headers["Authorization"] = f"Bearer {{auth_credential}}"
            """)

    body_block = ""
    request_call = ""
    if activity.method in ("POST", "PUT", "PATCH"):
        body_str = json.dumps(activity.body) if activity.body else "''"
        body_block = textwrap.dedent(f"""\
            body = dbutils.widgets.get("body") if dbutils.widgets.get("body") else {body_str}
        """)
        request_call = "response = requests.request(method, url, headers=headers, data=body, timeout=300)\n"
    else:
        request_call = "response = requests.request(method, url, headers=headers, timeout=300)\n"

    body = textwrap.dedent(f"""\
        import json
        import requests

        # Parameters
        url = dbutils.widgets.get("url") or "{activity.url}"
        method = dbutils.widgets.get("method") or "{activity.method}"
        headers = {headers_literal}

    """)
    body += auth_block
    body += body_block
    body += request_call
    body += textwrap.dedent("""\

        response.raise_for_status()

        # Return response
        try:
            result = response.json()
        except ValueError:
            result = {"status_code": response.status_code, "text": response.text}

        dbutils.notebook.exit(json.dumps(result))
    """)

    return header + _command_separator() + body


# ---------------------------------------------------------------------------
# Delete notebook
# ---------------------------------------------------------------------------


def generate_delete_notebook(activity: DeleteActivity) -> str:
    """Generate a notebook using dbutils.fs.rm().

    Args:
        activity: The DeleteActivity IR node.

    Returns:
        Complete notebook source code as a string.
    """
    header = _notebook_header(f"Delete: {activity.name}")
    folder_path = activity.folder_path or ""

    body = textwrap.dedent(f"""\
        # Parameters
        dataset_name = dbutils.widgets.get("dataset_name") or "{activity.dataset_name}"
        folder_path = dbutils.widgets.get("folder_path") or "{folder_path}"
        recursive = dbutils.widgets.get("recursive") == "true"

        # Build the full path to delete
        target_path = folder_path if folder_path else dataset_name
        print(f"Deleting: {{target_path}} (recursive={{recursive}})")
        result = dbutils.fs.rm(target_path, recurse=recursive)

        dbutils.notebook.exit(str(result))
    """)

    return header + _command_separator() + body


# ---------------------------------------------------------------------------
# Set variable notebook
# ---------------------------------------------------------------------------


def generate_set_variable_notebook(activity: SetVariableActivity) -> str:
    """Generate a notebook that sets a task value.

    Databricks jobs use ``dbutils.jobs.taskValues.set()`` as the equivalent
    of ADF pipeline variables, allowing downstream tasks to read values via
    ``dbutils.jobs.taskValues.get()``.

    Args:
        activity: The SetVariableActivity IR node.

    Returns:
        Complete notebook source code as a string.
    """
    header = _notebook_header(f"Set Variable: {activity.name}")

    body = textwrap.dedent(f"""\
        import json

        # Parameters
        variable_name = dbutils.widgets.get("variable_name") or "{activity.variable_name}"
        value = dbutils.widgets.get("value") or '''{activity.variable_value}'''

        # Set task value for downstream tasks
        dbutils.jobs.taskValues.set(key=variable_name, value=value)
        print(f"Set task value '{{variable_name}}' = '{{value}}'")

        dbutils.notebook.exit(json.dumps({{"variable_name": variable_name, "value": value}}))
    """)

    return header + _command_separator() + body


# ---------------------------------------------------------------------------
# Copy notebook
# ---------------------------------------------------------------------------

_FILE_SOURCE_TYPES = {
    "BlobSource",
    "AzureBlobFSSource",
    "AzureDataLakeStoreSource",
    "AmazonS3Source",
    "FileSystemSource",
    "SftpSource",
    "HttpSource",
    "AzureBlobStorageSource",
}

_JDBC_SOURCE_TYPES = {
    "AzureSqlSource",
    "SqlServerSource",
    "OracleSource",
    "PostgreSqlSource",
    "MySqlSource",
    "SqlSource",
    "CosmosDbSqlApiSource",
    "SqlDWSource",
    "AzureSqlDatabaseSource",
}

_REST_SOURCE_TYPES = {"RestSource", "HttpSource"}


def generate_copy_notebook(activity: CopyActivity) -> str:
    """Generate a notebook for copy operations (Auto Loader, COPY INTO, or JDBC).

    The ingestion strategy is chosen based on the source type string:
    - **File-based sources** (BlobSource, AzureBlobFSSource, etc.): Auto Loader
      for streaming ingestion into a Delta table.
    - **Database sources** (AzureSqlSource, SqlServerSource, etc.): JDBC read
      into a Delta table.
    - **REST sources**: HTTP-based ingestion.
    - **Other**: Fallback Spark read/write with configurable format.

    Args:
        activity: The CopyActivity IR node.

    Returns:
        Complete notebook source code as a string.
    """
    header = _notebook_header(f"Copy: {activity.name}")
    source_type = activity.source_type or ""

    if source_type in _FILE_SOURCE_TYPES:
        body = _generate_autoloader_body(activity)
    elif source_type in _JDBC_SOURCE_TYPES:
        body = _generate_jdbc_body(activity)
    elif source_type in _REST_SOURCE_TYPES:
        body = _generate_rest_copy_body(activity)
    else:
        body = _generate_generic_copy_body(activity)

    return header + _command_separator() + body


def _infer_file_format(source_properties: dict | None) -> str:
    """Infer the file format from source properties."""
    if not source_properties:
        return "parquet"
    # Check for format settings
    fmt_settings = source_properties.get("formatSettings", {})
    fmt_type = fmt_settings.get("type", "")
    if "Csv" in fmt_type or "Delimited" in fmt_type:
        return "csv"
    if "Json" in fmt_type:
        return "json"
    if "Parquet" in fmt_type:
        return "parquet"
    if "Avro" in fmt_type:
        return "avro"
    if "Orc" in fmt_type:
        return "orc"
    # Check storeSettings
    store = source_properties.get("storeSettings", {})
    store_type = store.get("type", "")
    if "BinaryRead" in store_type:
        return "binaryFile"
    return "parquet"


def _generate_autoloader_body(activity: CopyActivity) -> str:
    """Generate Auto Loader ingestion body for file-based sources."""
    src_props = activity.source_properties or {}
    sink_props = activity.sink_properties or {}

    source_path = src_props.get("path", src_props.get("filePath", "/mnt/source"))
    sink_table = sink_props.get("table", sink_props.get("tableName", f"{activity.task_key}_raw"))
    checkpoint = f"/tmp/checkpoints/{activity.task_key}"
    file_format = _infer_file_format(src_props)

    return textwrap.dedent(f"""\
        # Parameters
        source_path = dbutils.widgets.get("source_path") if dbutils.widgets.get("source_path") else "{source_path}"
        target_table = dbutils.widgets.get("target_table") if dbutils.widgets.get("target_table") else "{sink_table}"
        checkpoint_path = "{checkpoint}"

        # Auto Loader: stream file-based source into Delta table
        df = (
            spark.readStream.format("cloudFiles")
            .option("cloudFiles.format", "{file_format}")
            .option("cloudFiles.schemaLocation", checkpoint_path + "/_schema")
            .option("cloudFiles.inferColumnTypes", "true")
            .load(source_path)
        )

        # Write to Delta table
        (
            df.writeStream.format("delta")
            .option("checkpointLocation", checkpoint_path)
            .option("mergeSchema", "true")
            .outputMode("append")
            .trigger(availableNow=True)
            .toTable(target_table)
        )

        dbutils.notebook.exit(f"Auto Loader ingestion complete: {{target_table}}")
    """)


def _generate_jdbc_body(activity: CopyActivity) -> str:
    """Generate JDBC ingestion body for database sources."""
    scope = f"orchestra-{activity.task_key}"
    src_props = activity.source_properties or {}
    sink_props = activity.sink_properties or {}

    sink_table = sink_props.get("table", sink_props.get("tableName", f"{activity.task_key}_raw"))
    table_name = src_props.get("tableName", src_props.get("table", ""))
    query = src_props.get("sqlReaderQuery", src_props.get("query", ""))

    if table_name:
        read_option = f'    .option("dbtable", "{table_name}")'
    elif query:
        read_option = f'    .option("query", """{query}""")'
    else:
        read_option = '    .option("dbtable", "REPLACE_WITH_TABLE_NAME")'

    return textwrap.dedent(f"""\
        # Parameters
        target_table = dbutils.widgets.get("target_table") if dbutils.widgets.get("target_table") else "{sink_table}"

        # Credentials
        jdbc_url = dbutils.secrets.get(scope="{scope}", key="jdbc-url")
        jdbc_password = dbutils.secrets.get(scope="{scope}", key="jdbc-password")
        jdbc_user = dbutils.secrets.get(scope="{scope}", key="jdbc-user")

        # Read from source database via JDBC
        df = (
            spark.read.format("jdbc")
            .option("url", jdbc_url)
            .option("user", jdbc_user)
            .option("password", jdbc_password)
        {read_option}
            .load()
        )

        # Write to Delta table
        df.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target_table)

        print(f"JDBC ingestion complete: {{df.count()}} rows written to {{target_table}}")
        dbutils.notebook.exit(f"Rows written: {{df.count()}}")
    """)


def _generate_rest_copy_body(activity: CopyActivity) -> str:
    """Generate REST API ingestion body."""
    src_props = activity.source_properties or {}
    sink_props = activity.sink_properties or {}

    url = src_props.get("url", src_props.get("relativeUrl", ""))
    sink_table = sink_props.get("table", sink_props.get("tableName", f"{activity.task_key}_raw"))

    return textwrap.dedent(f"""\
        import json
        import requests

        # Parameters
        url = dbutils.widgets.get("url") if dbutils.widgets.get("url") else "{url}"
        target_table = dbutils.widgets.get("target_table") if dbutils.widgets.get("target_table") else "{sink_table}"
        headers = {{"Content-Type": "application/json"}}

        # Fetch data from REST API
        response = requests.get(url, headers=headers, timeout=300)
        response.raise_for_status()
        data = response.json()

        # Normalize to list of records
        if isinstance(data, dict):
            for key in ("value", "data", "results", "items", "records"):
                if key in data and isinstance(data[key], list):
                    data = data[key]
                    break
            else:
                data = [data]

        # Write to Delta table
        df = spark.createDataFrame(data)
        df.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target_table)

        print(f"REST ingestion complete: {{df.count()}} rows written to {{target_table}}")
        dbutils.notebook.exit(f"Rows written: {{df.count()}}")
    """)


def _generate_generic_copy_body(activity: CopyActivity) -> str:
    """Generate a generic Spark read/write copy body as fallback."""
    src_props = activity.source_properties or {}
    sink_props = activity.sink_properties or {}

    source_path = src_props.get("path", src_props.get("filePath", "/mnt/source"))
    sink_table = sink_props.get("table", sink_props.get("tableName", f"{activity.task_key}_raw"))
    file_format = _infer_file_format(src_props)

    return textwrap.dedent(f"""\
        # Parameters
        source_path = dbutils.widgets.get("source_path") if dbutils.widgets.get("source_path") else "{source_path}"
        target_table = dbutils.widgets.get("target_table") if dbutils.widgets.get("target_table") else "{sink_table}"

        # Read source data
        df = spark.read.format("{file_format}").load(source_path)

        # Write to Delta table
        df.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target_table)

        print(f"Copy complete: {{df.count()}} rows written to {{target_table}}")
        dbutils.notebook.exit(f"Rows written: {{df.count()}}")
    """)
