"""Generate Python notebook content for activities that need custom notebooks.

Each generator produces a self-contained Databricks notebook with:
- A ``# Databricks notebook source`` header
- Imports for required modules
- ``dbutils.widgets.get()`` for runtime parameters
- ``dbutils.secrets.get()`` for credentials
- ``dbutils.notebook.exit()`` to return results
"""

from __future__ import annotations

import json
import textwrap
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from orchestra.models.ir import (
        AppendVariableActivity,
        CopyActivity,
        DeleteActivity,
        FilterActivity,
        LookupActivity,
        SetVariableActivity,
        WaitActivity,
        WebActivity,
    )


def _notebook_header(title: str) -> str:
    """Return the standard Databricks notebook header block."""
    return textwrap.dedent(f"""\
        # Databricks notebook source
        # MAGIC %md
        # MAGIC # {title}
        # MAGIC
        # MAGIC *Auto-generated by Orchestra. Do not edit manually unless necessary.*
    """)


def _command_separator() -> str:
    """Return the Databricks cell separator comment."""
    return "\n# COMMAND ----------\n\n"


# ---------------------------------------------------------------------------
# Lookup notebook
# ---------------------------------------------------------------------------

_DB_SOURCE_TYPES = {
    "AzureSqlSource",
    "SqlServerSource",
    "OracleSource",
    "PostgreSqlSource",
    "MySqlSource",
    "SqlSource",
    "CosmosDbSqlApiSource",
    "SqlDWSource",
}


def generate_lookup_notebook(activity: LookupActivity, *, scope: str = "") -> str:
    """Generate a Python notebook that executes a lookup query.

    Args:
        activity: The LookupActivity IR node.
        scope: Secret scope name (defaults to task_key if empty).

    Returns:
        Complete notebook source code as a string.
    """
    header = _notebook_header(f"Lookup: {activity.name}")
    source_type = activity.source_type or ""
    query = activity.source_query or ""

    if source_type in _DB_SOURCE_TYPES:
        scope = scope or activity.task_key
        body = textwrap.dedent(f"""\
            import json

            # Parameters
            first_row_only = dbutils.widgets.get("first_row_only") == "true"

            # Credentials
            jdbc_url = dbutils.secrets.get(scope="{scope}", key="jdbc-url")
            jdbc_password = dbutils.secrets.get(scope="{scope}", key="jdbc-password")
            jdbc_user = dbutils.secrets.get(scope="{scope}", key="jdbc-user")

            # Execute lookup query
            query = \"\"\"{query}\"\"\"

            df = (
                spark.read.format("jdbc")
                .option("url", jdbc_url)
                .option("user", jdbc_user)
                .option("password", jdbc_password)
                .option("query", query)
                .load()
            )

            if first_row_only:
                result = df.first()
                output = result.asDict() if result else {{}}
            else:
                output = [row.asDict() for row in df.collect()]

            # Set task values so downstream tasks can reference them via
            # {{{{tasks.{activity.task_key}.values.<key>}}}}.
            # The full result is stored under "result".  For firstRow lookups,
            # each column is also stored as an individual task value so
            # condition_task can reference e.g. {{{{tasks.{activity.task_key}.values.cnt}}}}.
            dbutils.jobs.taskValues.set(key="result", value=output)
            if first_row_only and isinstance(output, dict):
                for col_name, col_value in output.items():
                    dbutils.jobs.taskValues.set(key=col_name, value=col_value)
            dbutils.notebook.exit(json.dumps(output))
        """)
    else:
        body = textwrap.dedent(f"""\
            import json

            # Parameters
            first_row_only = dbutils.widgets.get("first_row_only") == "true"

            # Execute lookup query via Spark SQL
            query = \"\"\"{query}\"\"\"
            df = spark.sql(query)

            if first_row_only:
                result = df.first()
                output = result.asDict() if result else {{}}
            else:
                output = [row.asDict() for row in df.collect()]

            # Set task values so downstream tasks can reference them via
            # {{{{tasks.{activity.task_key}.values.<key>}}}}.
            dbutils.jobs.taskValues.set(key="result", value=output)
            if first_row_only and isinstance(output, dict):
                for col_name, col_value in output.items():
                    dbutils.jobs.taskValues.set(key=col_name, value=col_value)
            dbutils.notebook.exit(json.dumps(output))
        """)

    return header + _command_separator() + body


# ---------------------------------------------------------------------------
# Web activity notebook
# ---------------------------------------------------------------------------


def _dab_ref_to_fstring_expr(ref: str) -> str:
    """Convert a DAB ref like {{job.name}} to a Python f-string expression.

    Args:
        ref: A DAB dynamic value reference string.

    Returns:
        A Python f-string expression like ``{dbutils.widgets.get('name')}``.
    """
    import re as _re

    m = _re.match(r"\{\{job\.parameters\.(\w+)\}\}", ref)
    if m:
        return "{dbutils.widgets.get('" + m.group(1) + "')}"
    m = _re.match(r"\{\{job\.run_id\}\}", ref)
    if m:
        return "{spark.conf.get('spark.databricks.job.runId', 'unknown')}"
    m = _re.match(r"\{\{job\.name\}\}", ref)
    if m:
        return "{spark.conf.get('spark.databricks.job.parentName', 'unknown')}"
    m = _re.match(r"\{\{job\.start_time\.iso_datetime\}\}", ref)
    if m:
        return "{spark.conf.get('spark.databricks.job.triggerTime', 'unknown')}"
    m = _re.match(r"\{\{tasks\.([^.]+)\.values\.(\w+)\}\}", ref)
    if m:
        return "{dbutils.jobs.taskValues.get(taskKey='" + m.group(1) + "', key='" + m.group(2) + "')}"
    return ref


def _resolve_body(body: Any) -> str:
    """Resolve ADF expressions in a request body and return a Python literal.

    Walks the body dict/list/string and resolves any ADF expression values
    (``@{...}`` interpolation or ``{"type": "Expression", ...}`` dicts) to
    Python code or literal strings.

    Args:
        body: The raw body from the WebActivity IR.

    Returns:
        A Python expression string suitable for embedding in generated code.
    """
    if body is None:
        return "''"

    from orchestra.models.ir import TranslationContext
    from orchestra.parser.expression_parser import (
        resolve_expression,
        resolve_interpolated_string_for_notebook,
    )

    ctx = TranslationContext()

    if isinstance(body, str):
        if "@{" in body:
            resolved_str = resolve_interpolated_string_for_notebook(body, ctx)
            return f"f{repr(resolved_str)}"
        if body.startswith("@"):
            result = resolve_expression(body, ctx)
            if result and result.kind == "literal":
                return repr(result.value)
        return repr(body)

    if isinstance(body, dict):
        # Check if any values need runtime resolution (DAB refs or expressions).
        # If so, build the dict as a Python expression using f-strings.
        needs_fstring = False
        resolved: dict[str, Any] = {}
        for k, v in body.items():
            if isinstance(v, str) and "@{" in v:
                needs_fstring = True
                resolved[k] = resolve_interpolated_string_for_notebook(v, ctx)
            elif isinstance(v, str) and v.startswith("@"):
                result = resolve_expression(v, ctx)
                if result and result.kind == "dab_ref":
                    needs_fstring = True
                    resolved[k] = _dab_ref_to_fstring_expr(result.value)
                elif result and result.kind == "literal":
                    resolved[k] = result.value
                else:
                    resolved[k] = v
            elif isinstance(v, dict) and v.get("type") == "Expression":
                result = resolve_expression(v, ctx)
                if result and result.kind == "dab_ref":
                    needs_fstring = True
                    resolved[k] = _dab_ref_to_fstring_expr(result.value)
                elif result and result.kind == "literal":
                    resolved[k] = result.value
                else:
                    resolved[k] = v.get("value", str(v))
            else:
                resolved[k] = v

        if needs_fstring:
            # Build a Python dict literal with f-string expressions
            parts = []
            for k, v in resolved.items():
                if isinstance(v, str) and "{" in v and "dbutils" in v:
                    parts.append(f'"{k}": f"{v}"')
                else:
                    parts.append(f'"{k}": {json.dumps(v)}')
            return "{" + ", ".join(parts) + "}"
        return json.dumps(resolved)

    return json.dumps(body) if body else "''"


def _resolve_headers(headers: dict[str, str] | None) -> tuple[str, str]:
    """Resolve ADF expressions in HTTP header values.

    Header values may be plain strings or ADF expression dicts like
    ``{"type": "Expression", "value": "@concat('Bearer ', ...)"}``.

    Returns:
        A tuple of ``(headers_literal, preamble_code)``:
        - ``headers_literal`` is a Python dict literal for the initial headers
        - ``preamble_code`` is Python code to execute after the headers dict
          is created, adding dynamically computed header values
    """
    if not headers:
        return "{}", ""

    from orchestra.models.ir import TranslationContext
    from orchestra.parser.expression_parser import resolve_expression

    ctx = TranslationContext()
    static_headers: dict[str, str] = {}
    preamble_lines: list[str] = []

    for key, value in headers.items():
        result = resolve_expression(value, ctx)
        if result is None:
            # Unresolvable — keep as literal string representation
            static_headers[key] = str(value) if not isinstance(value, str) else value
        elif result.kind == "literal":
            static_headers[key] = result.value
        elif result.kind == "dab_ref":
            # DAB ref in a header value — read from widget at runtime
            preamble_lines.append(f'headers["{key}"] = dbutils.widgets.get("{key}")')
        elif result.kind == "notebook_code":
            # Python code — compute the value at runtime
            for imp in result.imports:
                preamble_lines.insert(0, imp)
            preamble_lines.append(f'headers["{key}"] = {result.value}')

    headers_literal = json.dumps(static_headers) if static_headers else "{}"
    preamble = ""
    if preamble_lines:
        # Deduplicate imports
        seen: set[str] = set()
        unique_lines: list[str] = []
        for line in preamble_lines:
            if line not in seen:
                seen.add(line)
                unique_lines.append(line)
        preamble = "\n".join(unique_lines) + "\n"

    return headers_literal, preamble


def generate_web_activity_notebook(activity: WebActivity, *, scope: str = "") -> str:
    """Generate a Python notebook that makes an HTTP request.

    Args:
        activity: The WebActivity IR node.
        scope: Secret scope name (defaults to task_key if empty).

    Returns:
        Complete notebook source code as a string.
    """
    header = _notebook_header(f"Web Activity: {activity.name}")

    # Resolve header values — some may contain ADF expressions like
    # {"Authorization": {"type": "Expression", "value": "@concat('Bearer ', ...)"}}
    headers_literal, headers_preamble = _resolve_headers(activity.headers)

    auth_block = ""
    auth = activity.authentication
    if auth:
        scope = scope or activity.task_key
        auth_type = auth.get("type", "")
        if auth_type in ("ServicePrincipal", "MSI", "ManagedServiceIdentity"):
            auth_block = textwrap.dedent(f"""\
                # Authentication ({auth_type})
                auth_token = dbutils.secrets.get(scope="{scope}", key="auth-credential")
                headers["Authorization"] = f"Bearer {{auth_token}}"
            """)
        elif auth_type == "Basic":
            auth_block = textwrap.dedent(f"""\
                # Authentication (Basic)
                import base64
                username = dbutils.secrets.get(scope="{scope}", key="auth-username")
                password = dbutils.secrets.get(scope="{scope}", key="auth-credential")
                token = base64.b64encode(f"{{username}}:{{password}}".encode()).decode()
                headers["Authorization"] = f"Basic {{token}}"
            """)
        else:
            auth_block = textwrap.dedent(f"""\
                # Authentication
                auth_credential = dbutils.secrets.get(scope="{scope}", key="auth-credential")
                headers["Authorization"] = f"Bearer {{auth_credential}}"
            """)

    body_block = ""
    request_call = ""
    if activity.method in ("POST", "PUT", "PATCH"):
        body_str = _resolve_body(activity.body)
        body_block = textwrap.dedent(f"""\
            body = dbutils.widgets.get("body") if dbutils.widgets.get("body") else {body_str}
        """)
        request_call = "response = requests.request(method, url, headers=headers, data=body, timeout=300)\n"
    else:
        request_call = "response = requests.request(method, url, headers=headers, timeout=300)\n"

    body = textwrap.dedent(f"""\
        import json
        import requests

        # Parameters
        url = dbutils.widgets.get("url") or "{activity.url}"
        method = dbutils.widgets.get("method") or "{activity.method}"
        headers = {headers_literal}

    """)
    body += headers_preamble
    body += auth_block
    body += body_block
    body += request_call
    body += textwrap.dedent("""\

        response.raise_for_status()

        # Return response
        try:
            result = response.json()
        except ValueError:
            result = {"status_code": response.status_code, "text": response.text}

        dbutils.notebook.exit(json.dumps(result))
    """)

    return header + _command_separator() + body


# ---------------------------------------------------------------------------
# Delete notebook
# ---------------------------------------------------------------------------


def generate_delete_notebook(activity: DeleteActivity) -> str:
    """Generate a notebook using dbutils.fs.rm().

    Args:
        activity: The DeleteActivity IR node.

    Returns:
        Complete notebook source code as a string.
    """
    header = _notebook_header(f"Delete: {activity.name}")
    folder_path = activity.folder_path or ""

    body = textwrap.dedent(f"""\
        # Parameters
        dataset_name = dbutils.widgets.get("dataset_name") or "{activity.dataset_name}"
        folder_path = dbutils.widgets.get("folder_path") or "{folder_path}"
        recursive = dbutils.widgets.get("recursive") == "true"

        # Build the full path to delete
        target_path = folder_path if folder_path else dataset_name
        print(f"Deleting: {{target_path}} (recursive={{recursive}})")
        result = dbutils.fs.rm(target_path, recurse=recursive)

        dbutils.notebook.exit(str(result))
    """)

    return header + _command_separator() + body


# ---------------------------------------------------------------------------
# Set variable notebook
# ---------------------------------------------------------------------------


def generate_set_variable_notebook(activity: SetVariableActivity) -> str:
    """Generate a notebook that sets a task value.

    Databricks jobs use ``dbutils.jobs.taskValues.set()`` as the equivalent
    of ADF pipeline variables, allowing downstream tasks to read values via
    ``dbutils.jobs.taskValues.get()`` or ``{{tasks.<key>.values.<name>}}``.

    When ``value_kind`` is ``"literal"`` or ``"dab_ref"`` the value is read
    from the ``value`` widget parameter (passed via ``base_parameters``).

    When ``value_kind`` is ``"notebook_code"`` the Python code is embedded
    directly in the notebook body -- no executable code in parameters.

    Args:
        activity: The SetVariableActivity IR node.

    Returns:
        Complete notebook source code as a string.
    """
    header = _notebook_header(f"Set Variable: {activity.name}")

    if activity.value_kind == "notebook_code" and activity.notebook_code:
        # Embed imports and Python code directly in the notebook
        import_lines = "\n".join(activity.notebook_imports) if activity.notebook_imports else ""
        if import_lines:
            import_block = import_lines + "\n"
        else:
            import_block = ""

        # Build body lines list to avoid textwrap.dedent issues when
        # import_block starts at column 0 (which would prevent dedent
        # from stripping the common leading whitespace).
        lines = ["import json"]
        if import_block:
            lines.append(import_block.rstrip("\n"))
        lines.append("")
        lines.append(f'variable_name = "{activity.variable_name}"')
        lines.append("")
        lines.append("# Compute value at runtime.")
        lines.append("# Original ADF expression resolved to notebook code.")
        lines.append(f"value = {activity.notebook_code}")
        lines.append("")
        lines.append("# Set task value so downstream tasks can reference it via")
        lines.append(f"# {{{{tasks.{activity.task_key}.values.{activity.variable_name}}}}}.")
        lines.append("dbutils.jobs.taskValues.set(key=variable_name, value=value)")
        lines.append("print(f\"Set task value '{variable_name}' = '{value}'\")")
        lines.append("")
        lines.append('dbutils.notebook.exit(json.dumps({"variable_name": variable_name, "value": str(value)}))')
        body = "\n".join(lines) + "\n"
    else:
        # literal or dab_ref: read from widget parameter
        body = textwrap.dedent(f"""\
            import json

            variable_name = "{activity.variable_name}"

            # Read value from widget parameter (set via base_parameters).
            # DAB resolves dynamic references (e.g. {{{{job.run_id}}}}) before passing.
            value = dbutils.widgets.get("value")

            # Set task value so downstream tasks can reference it via
            # {{{{tasks.{activity.task_key}.values.{activity.variable_name}}}}}.
            dbutils.jobs.taskValues.set(key=variable_name, value=value)
            print(f"Set task value '{{variable_name}}' = '{{value}}'")

            dbutils.notebook.exit(json.dumps({{"variable_name": variable_name, "value": str(value)}}))
        """)

    return header + _command_separator() + body


# ---------------------------------------------------------------------------
# Wait notebook
# ---------------------------------------------------------------------------


def generate_wait_notebook(activity: WaitActivity) -> str:
    """Generate a notebook that sleeps for a specified duration.

    ADF Wait activities pause pipeline execution for N seconds.  The
    Databricks equivalent is a simple ``time.sleep()`` call inside a
    generated notebook.

    Args:
        activity: The WaitActivity IR node.

    Returns:
        Complete notebook source code as a string.
    """
    header = _notebook_header(f"Wait: {activity.name}")

    body = textwrap.dedent(f"""\
        import time

        # Parameters
        default_wait = {activity.wait_time_seconds}
        param = dbutils.widgets.get("wait_seconds")
        wait_seconds = int(param) if param else default_wait

        print(f"Waiting for {{wait_seconds}} seconds...")
        time.sleep(wait_seconds)
        print("Wait complete.")

        dbutils.notebook.exit(f"Waited {{wait_seconds}} seconds")
    """)

    return header + _command_separator() + body


# ---------------------------------------------------------------------------
# Copy notebook
# ---------------------------------------------------------------------------

_FILE_SOURCE_TYPES = {
    "BlobSource",
    "AzureBlobFSSource",
    "AzureDataLakeStoreSource",
    "AmazonS3Source",
    "FileSystemSource",
    "SftpSource",
    "HttpSource",
    "AzureBlobStorageSource",
    "DelimitedTextSource",
    "JsonSource",
    "ParquetSource",
    "AvroSource",
    "OrcSource",
}

_JDBC_SOURCE_TYPES = {
    "AzureSqlSource",
    "SqlServerSource",
    "OracleSource",
    "PostgreSqlSource",
    "MySqlSource",
    "SqlSource",
    "CosmosDbSqlApiSource",
    "SqlDWSource",
    "AzureSqlDatabaseSource",
}

_REST_SOURCE_TYPES = {"RestSource", "HttpSource"}


def generate_copy_notebook(activity: CopyActivity, *, scope: str = "") -> str:
    """Generate a notebook for copy operations (Auto Loader, COPY INTO, or JDBC).

    The ingestion strategy is chosen based on the source type string:
    - **File-based sources** (BlobSource, AzureBlobFSSource, etc.): Auto Loader
      for streaming ingestion into a Delta table.
    - **Database sources** (AzureSqlSource, SqlServerSource, etc.): JDBC read
      into a Delta table.
    - **REST sources**: HTTP-based ingestion.
    - **Other**: Fallback Spark read/write with configurable format.

    Args:
        activity: The CopyActivity IR node.
        scope: Secret scope name (defaults to task_key if empty).

    Returns:
        Complete notebook source code as a string.
    """
    header = _notebook_header(f"Copy: {activity.name}")
    source_type = activity.source_type or ""

    if source_type in _FILE_SOURCE_TYPES:
        body = _generate_autoloader_body(activity)
    elif source_type in _JDBC_SOURCE_TYPES:
        body = _generate_jdbc_body(activity, scope=scope)
    elif source_type in _REST_SOURCE_TYPES:
        body = _generate_rest_copy_body(activity)
    else:
        body = _generate_generic_copy_body(activity)

    return header + _command_separator() + body


def _infer_file_format(source_type: str | None, source_properties: dict | None) -> str:
    """Infer the file format from the source type string and source properties.

    Checks the source_type string first (most reliable), then falls back to
    format settings in source_properties.

    Args:
        source_type: The ADF source type string (e.g. ``"DelimitedTextSource"``).
        source_properties: The source properties dict from the CopyActivity.

    Returns:
        File format string (e.g. ``"csv"``, ``"json"``, ``"parquet"``).
    """
    # Check source type string first -- most reliable
    if source_type:
        type_lower = source_type.lower()
        if "delimitedtext" in type_lower or "csv" in type_lower:
            return "csv"
        if "json" in type_lower:
            return "json"
        if "parquet" in type_lower:
            return "parquet"
        if "avro" in type_lower:
            return "avro"
        if "orc" in type_lower:
            return "orc"

    # Then check formatSettings in source properties
    if source_properties:
        fmt_settings = source_properties.get("formatSettings", {})
        fmt_type = fmt_settings.get("type", "")
        if "Csv" in fmt_type or "Delimited" in fmt_type:
            return "csv"
        if "Json" in fmt_type:
            return "json"
        if "Parquet" in fmt_type:
            return "parquet"
        if "Avro" in fmt_type:
            return "avro"
        if "Orc" in fmt_type:
            return "orc"
        # Check storeSettings
        store = source_properties.get("storeSettings", {})
        store_type = store.get("type", "")
        if "BinaryRead" in store_type:
            return "binaryFile"

    # Default based on source type
    return "parquet"


def _generate_autoloader_body(activity: CopyActivity) -> str:
    """Generate Auto Loader ingestion body for file-based sources."""
    src_props = activity.source_properties or {}
    sink_props = activity.sink_properties or {}

    # Prefer the UC volume path when available (set by the copy preparer
    # when an external volume setup task is created); otherwise fall back
    # to the resolved abfss:// path or raw dataset path.
    source_path = src_props.get(
        "volume_path",
        src_props.get(
            "resolved_path",
            src_props.get("path", src_props.get("filePath", "/mnt/source")),
        ),
    )
    sink_table = sink_props.get("table", sink_props.get("tableName", f"{activity.task_key}_raw"))
    file_format = _infer_file_format(activity.source_type, src_props)

    # Use the volume for checkpoints and schema evolution storage instead of
    # /tmp.  This ensures state persists across cluster restarts and is
    # visible in Unity Catalog.
    volume_base = src_props.get("volume_base", "")
    if volume_base:
        checkpoint = f"{volume_base}/_checkpoints/{activity.task_key}"
    else:
        checkpoint = f"/tmp/checkpoints/{activity.task_key}"

    return textwrap.dedent(f"""\
        # Parameters
        source_path = dbutils.widgets.get("source_path") if dbutils.widgets.get("source_path") else "{source_path}"
        target_table = dbutils.widgets.get("target_table") if dbutils.widgets.get("target_table") else "{sink_table}"
        checkpoint_path = "{checkpoint}"

        # Auto Loader: stream file-based source into Delta table
        df = (
            spark.readStream.format("cloudFiles")
            .option("cloudFiles.format", "{file_format}")
            .option("cloudFiles.schemaLocation", checkpoint_path + "/_schema")
            .option("cloudFiles.inferColumnTypes", "true")
            .load(source_path)
        )

        # Write to Delta table
        (
            df.writeStream.format("delta")
            .option("checkpointLocation", checkpoint_path)
            .option("mergeSchema", "true")
            .outputMode("append")
            .trigger(availableNow=True)
            .toTable(target_table)
        )

        dbutils.notebook.exit(f"Auto Loader ingestion complete: {{target_table}}")
    """)


def _generate_jdbc_body(activity: CopyActivity, *, scope: str = "") -> str:
    """Generate JDBC ingestion body for database sources.

    When the SQL query contains an ADF expression like
    ``@concat('SELECT * FROM ', item().schema_name, '.', item().table_name)``,
    the notebook is parameterized to accept an ``item`` widget (passed from
    a ForEach task via ``{{input}}``) and build the query dynamically.
    """
    scope = scope or activity.task_key
    src_props = activity.source_properties or {}
    sink_props = activity.sink_properties or {}

    sink_table = sink_props.get("table", sink_props.get("tableName", f"{activity.task_key}_raw"))
    table_name = src_props.get("tableName", src_props.get("table", ""))
    query_raw = src_props.get("sqlReaderQuery", src_props.get("query", ""))

    # Detect ADF expression dicts that weren't resolved during translation
    query = ""
    is_expression = False
    if isinstance(query_raw, dict) and query_raw.get("type") == "Expression":
        is_expression = True
        query = query_raw.get("value", "")
    elif isinstance(query_raw, str):
        query = query_raw
        if query.startswith("@"):
            is_expression = True

    if is_expression:
        # The query is an ADF expression (e.g. @concat('SELECT * FROM ', item().schema_name, ...)).
        # Generate a notebook that reads the current ForEach item from the
        # "item" widget (set to {{input}} by the for_each_task) and builds
        # the SQL query dynamically.
        return textwrap.dedent(f"""\
            import json

            # Parameters
            default_table = "{sink_table}"
            target_table = dbutils.widgets.get("target_table") or default_table

            # The ForEach task passes the current item as the "item" widget
            # parameter via {{{{input}}}}.  Parse it as JSON to access fields.
            item_raw = dbutils.widgets.get("item")
            item = json.loads(item_raw) if item_raw else {{}}

            # Credentials
            jdbc_url = dbutils.secrets.get(scope="{scope}", key="jdbc-url")
            jdbc_password = dbutils.secrets.get(scope="{scope}", key="jdbc-password")
            jdbc_user = dbutils.secrets.get(scope="{scope}", key="jdbc-user")

            # Build the SQL query from the ForEach item fields.
            # Original ADF expression: {query}
            schema_name = item.get("schema_name", "dbo")
            table_name = item.get("table_name", "UNKNOWN_TABLE")
            query = f"SELECT * FROM {{schema_name}}.{{table_name}}"
            print(f"Executing query: {{query}}")

            # Read from source database via JDBC
            df = (
                spark.read.format("jdbc")
                .option("url", jdbc_url)
                .option("user", jdbc_user)
                .option("password", jdbc_password)
                .option("query", query)
                .load()
            )

            # Write to Delta table (append for ForEach pattern)
            df.write.format("delta").mode("append").option("mergeSchema", "true").saveAsTable(target_table)

            print(f"JDBC ingestion complete: {{df.count()}} rows written to {{target_table}}")
            dbutils.notebook.exit(f"Rows written: {{df.count()}}")
        """)

    # Static query or table name — resolve any @{...} interpolation in SQL strings
    if table_name:
        read_option = f'    .option("dbtable", "{table_name}")'
    elif query:
        if "@{" in query:
            from orchestra.models.ir import TranslationContext as _TC
            from orchestra.parser.expression_parser import resolve_interpolated_string_for_notebook as _risn

            resolved_query = _risn(query, _TC())
            # The resolved query uses f-string expressions for runtime parameter access.
            read_option = f'    .option("query", f"""{resolved_query}""")'
        else:
            read_option = f'    .option("query", """{query}""")'
    else:
        read_option = '    .option("dbtable", "REPLACE_WITH_TABLE_NAME")'

    return textwrap.dedent(f"""\
        # Parameters
        target_table = dbutils.widgets.get("target_table") if dbutils.widgets.get("target_table") else "{sink_table}"

        # Credentials
        jdbc_url = dbutils.secrets.get(scope="{scope}", key="jdbc-url")
        jdbc_password = dbutils.secrets.get(scope="{scope}", key="jdbc-password")
        jdbc_user = dbutils.secrets.get(scope="{scope}", key="jdbc-user")

        # Read from source database via JDBC
        df = (
            spark.read.format("jdbc")
            .option("url", jdbc_url)
            .option("user", jdbc_user)
            .option("password", jdbc_password)
        {read_option}
            .load()
        )

        # Write to Delta table
        df.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target_table)

        print(f"JDBC ingestion complete: {{df.count()}} rows written to {{target_table}}")
        dbutils.notebook.exit(f"Rows written: {{df.count()}}")
    """)


def _generate_rest_copy_body(activity: CopyActivity) -> str:
    """Generate REST API ingestion body."""
    src_props = activity.source_properties or {}
    sink_props = activity.sink_properties or {}

    url = src_props.get("url", src_props.get("relativeUrl", ""))
    sink_table = sink_props.get("table", sink_props.get("tableName", f"{activity.task_key}_raw"))

    return textwrap.dedent(f"""\
        import json
        import requests

        # Parameters
        url = dbutils.widgets.get("url") if dbutils.widgets.get("url") else "{url}"
        target_table = dbutils.widgets.get("target_table") if dbutils.widgets.get("target_table") else "{sink_table}"
        headers = {{"Content-Type": "application/json"}}

        # Fetch data from REST API
        response = requests.get(url, headers=headers, timeout=300)
        response.raise_for_status()
        data = response.json()

        # Normalize to list of records
        if isinstance(data, dict):
            for key in ("value", "data", "results", "items", "records"):
                if key in data and isinstance(data[key], list):
                    data = data[key]
                    break
            else:
                data = [data]

        # Write to Delta table
        df = spark.createDataFrame(data)
        df.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target_table)

        print(f"REST ingestion complete: {{df.count()}} rows written to {{target_table}}")
        dbutils.notebook.exit(f"Rows written: {{df.count()}}")
    """)


def _generate_generic_copy_body(activity: CopyActivity) -> str:
    """Generate a generic Spark read/write copy body as fallback."""
    src_props = activity.source_properties or {}
    sink_props = activity.sink_properties or {}

    # Use the resolved path from dataset if available, otherwise fall back
    source_path = src_props.get(
        "resolved_path",
        src_props.get("path", src_props.get("filePath", "/mnt/source")),
    )
    sink_table = sink_props.get("table", sink_props.get("tableName", f"{activity.task_key}_raw"))
    file_format = _infer_file_format(activity.source_type, src_props)

    return textwrap.dedent(f"""\
        # Parameters
        source_path = dbutils.widgets.get("source_path") if dbutils.widgets.get("source_path") else "{source_path}"
        target_table = dbutils.widgets.get("target_table") if dbutils.widgets.get("target_table") else "{sink_table}"

        # Read source data
        df = spark.read.format("{file_format}").load(source_path)

        # Write to Delta table
        df.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target_table)

        print(f"Copy complete: {{df.count()}} rows written to {{target_table}}")
        dbutils.notebook.exit(f"Rows written: {{df.count()}}")
    """)


# ---------------------------------------------------------------------------
# Filter notebook
# ---------------------------------------------------------------------------


def generate_filter_notebook(activity: FilterActivity) -> str:
    """Generate a notebook that filters an array and stores the result as a task value.

    The notebook reads the input array from a task value or parameter, applies
    the filter condition, and writes the filtered result via
    ``dbutils.jobs.taskValues.set()``.

    Args:
        activity: The FilterActivity IR node.

    Returns:
        Complete notebook source code as a string.
    """
    header = _notebook_header(f"Filter: {activity.name}")

    body = textwrap.dedent(f"""\
        import json

        # Parameters
        items_expression = dbutils.widgets.get("items_expression") or '''{activity.items_expression}'''
        condition_expression = dbutils.widgets.get("condition_expression") or '''{activity.condition_expression}'''

        # Evaluate the input array
        # If the items expression is a task value reference, evaluate it;
        # otherwise treat it as a JSON-encoded list.
        try:
            items = eval(items_expression)
        except Exception:
            items = json.loads(items_expression)

        if not isinstance(items, list):
            items = list(items) if hasattr(items, '__iter__') else [items]

        # Apply the filter condition
        # The condition expression should be a Python lambda or expression string.
        # For ADF @equals(item().status, 'active') style conditions, we wrap in a
        # lambda that receives each item.
        try:
            filter_fn = eval(f"lambda item: {{condition_expression}}")
            filtered = [item for item in items if filter_fn(item)]
        except Exception:
            # Fallback: keep all items if the condition cannot be evaluated
            print(f"WARNING: Could not evaluate filter condition: {{condition_expression}}")
            print("Returning all items unfiltered. Please review the condition expression.")
            filtered = items

        # Set the filtered result as a task value for downstream tasks
        result = json.dumps(filtered)
        dbutils.jobs.taskValues.set(key="output", value=result)
        print(f"Filtered {{len(items)}} items to {{len(filtered)}} items")

        dbutils.notebook.exit(result)
    """)

    return header + _command_separator() + body


# ---------------------------------------------------------------------------
# Append variable notebook
# ---------------------------------------------------------------------------


def generate_append_variable_notebook(activity: AppendVariableActivity) -> str:
    """Generate a notebook that appends a value to an array task value.

    Reads the current array from a task value (or initialises an empty list),
    appends the new value, and writes the updated array back via
    ``dbutils.jobs.taskValues.set()``.

    When ``value_kind`` is ``"notebook_code"`` the Python code is embedded
    directly -- no executable code in parameters.

    Args:
        activity: The AppendVariableActivity IR node.

    Returns:
        Complete notebook source code as a string.
    """
    header = _notebook_header(f"Append Variable: {activity.name}")

    if activity.value_kind == "notebook_code" and activity.notebook_code:
        import_lines = "\n".join(activity.notebook_imports) if activity.notebook_imports else ""
        if import_lines:
            import_block = import_lines + "\n"
        else:
            import_block = ""

        # Build body lines list to avoid textwrap.dedent issues when
        # import_block starts at column 0.
        lines = ["import json"]
        if import_block:
            lines.append(import_block.rstrip("\n"))
        lines.append("")
        lines.append("# Parameters")
        lines.append(f'variable_name = dbutils.widgets.get("variable_name") or "{activity.variable_name}"')
        lines.append("")
        lines.append("# Compute value at runtime.")
        lines.append(f"value = {activity.notebook_code}")
        lines.append("")
        lines.append("# Read the current array from task values (or start with empty list)")
        lines.append("try:")
        lines.append('    tk = dbutils.widgets.get("task_key", "")')
        lines.append("    current_raw = dbutils.jobs.taskValues.get(taskKey=tk, key=variable_name)")
        lines.append("    if isinstance(current_raw, str):")
        lines.append("        current = json.loads(current_raw)")
        lines.append("    else:")
        lines.append("        current = current_raw")
        lines.append("except Exception:")
        lines.append("    current = []")
        lines.append("")
        lines.append("if not isinstance(current, list):")
        lines.append("    current = [current] if current else []")
        lines.append("")
        lines.append("# Append and write back")
        lines.append("current.append(value)")
        lines.append("result = json.dumps(current)")
        lines.append("dbutils.jobs.taskValues.set(key=variable_name, value=result)")
        lines.append("print(f\"Appended to '{variable_name}': array now has {len(current)} item(s)\")")
        lines.append("")
        lines.append("dbutils.notebook.exit(result)")
        body = "\n".join(lines) + "\n"
    else:
        body = textwrap.dedent(f"""\
            import json

            # Parameters
            variable_name = dbutils.widgets.get("variable_name") or "{activity.variable_name}"
            value = dbutils.widgets.get("value") or {json.dumps(activity.append_value)}

            # Read the current array from task values (or start with empty list)
            try:
                tk = dbutils.widgets.get("task_key", "")
                current_raw = dbutils.jobs.taskValues.get(taskKey=tk, key=variable_name)
                if isinstance(current_raw, str):
                    current = json.loads(current_raw)
                else:
                    current = current_raw
            except Exception:
                current = []

            if not isinstance(current, list):
                current = [current] if current else []

            # Evaluate the value to append
            try:
                starts = ('{{', '[', '"')
                append_val = json.loads(value) if isinstance(value, str) and value.startswith(starts) else value
            except (json.JSONDecodeError, ValueError):
                append_val = value

            # Append and write back
            current.append(append_val)
            result = json.dumps(current)
            dbutils.jobs.taskValues.set(key=variable_name, value=result)
            print(f"Appended to '{{variable_name}}': array now has {{len(current)}} item(s)")

            dbutils.notebook.exit(result)
        """)

    return header + _command_separator() + body
