"""Convert a translated Pipeline IR into a PreparedWorkflow.

The PreparedWorkflow contains task dicts, generated notebooks, secret
instructions, and setup tasks ready for the DAB bundle writer.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from orchestra.models.dab import DabNotebook, SecretInstruction, SetupTask
from orchestra.models.ir import (
    Activity,
    AppendVariableActivity,
    CopyActivity,
    DeleteActivity,
    ExecutePipelineActivity,
    FilterActivity,
    ForEachActivity,
    IfConditionActivity,
    LookupActivity,
    NotebookActivity,
    Pipeline,
    PlaceholderActivity,
    RunJobActivity,
    SetVariableActivity,
    SparkJarActivity,
    SparkPythonActivity,
    SwitchActivity,
    UnsupportedActivity,
    WaitActivity,
    WebActivity,
)


@dataclass(slots=True, kw_only=True)
class PreparedActivity:
    """Result of preparing a single activity for DAB deployment.

    Attributes:
        task: The DAB task dict ready for inclusion in a job definition.
        extra_tasks: Additional sibling tasks emitted by this activity.  Used
            by IfCondition and Switch to flatten branch children into the
            job's top-level task list (per the DAB condition_task schema,
            which has no nested task children — branching is expressed via
            ``depends_on.outcome``).
        notebooks: Generated notebooks this task depends on.
        secrets: Secret creation instructions required by this task.
        setup_tasks: One-time setup tasks required before this task can run.
        inner_workflows: Nested workflows generated by ForEach activities that
            need a separate inner job for their multi-step task graph.
    """

    task: dict[str, Any]
    extra_tasks: list[dict[str, Any]] = field(default_factory=list)
    notebooks: list[DabNotebook] = field(default_factory=list)
    secrets: list[SecretInstruction] = field(default_factory=list)
    setup_tasks: list[SetupTask] = field(default_factory=list)
    inner_workflows: list[PreparedWorkflow] = field(default_factory=list)
    # Optional rename mapping from a logical task_key (set on the IR activity)
    # to the actual emitted entry-point task_key.  Used by Switch when the
    # first case task is renamed to ``<activity>__case_<value>`` for clarity:
    # any downstream task whose ``depends_on`` references the original
    # ``<activity>`` key is rewritten to point at the new first-case key by
    # ``prepare_workflow``.
    task_key_remap: dict[str, str] = field(default_factory=dict)


@dataclass(slots=True, kw_only=True)
class PreparedWorkflow:
    """A fully prepared workflow ready for DAB bundle generation.

    Attributes:
        name: Human-readable workflow name.
        tasks: Ordered list of DAB task dicts.
        notebooks: All generated notebooks needed by the workflow.
        secrets: All secret instructions aggregated across tasks.
        setup_tasks: All one-time setup tasks aggregated across tasks.
        inner_workflows: Nested workflows (from ForEach / ExecutePipeline activities).
        parameters: Job-level parameter declarations (name + optional default).
            Used by inner jobs that receive inputs from a parent for_each_task.
    """

    name: str
    tasks: list[dict[str, Any]]
    notebooks: list[DabNotebook]
    secrets: list[SecretInstruction]
    setup_tasks: list[SetupTask]
    inner_workflows: list[PreparedWorkflow] = field(default_factory=list)
    parameters: list[dict[str, Any]] = field(default_factory=list)
    # Per-task cluster hints (``{"spark_version": ..., "node_type_id": ...}``)
    # collected from the activities' ADF linked-service configs.  Preserved
    # so the bundle writer can pin ``spark_version`` / ``node_type_id``
    # defaults to values the source pipeline was authored against.
    cluster_hints: list[dict[str, Any]] = field(default_factory=list)


def _run_if_from_adf_outcomes(outcomes: list[str | None]) -> str | None:
    """Map the set of ADF dependency conditions to a single DAB ``run_if``.

    ADF lets each dependency edge carry its own outcome (``Succeeded`` /
    ``Failed`` / ``Completed`` / ``Skipped``).  DAB models this as a single
    ``run_if`` on the *downstream* task ([control flow docs](https://docs.databricks.com/aws/en/jobs/run-if)),
    so we combine the edges with the most permissive rule that preserves
    ADF semantics:

    - Any ``Completed`` or ``Skipped`` → ``ALL_DONE`` (downstream fires
      regardless of upstream result).
    - Any ``Failed`` → ``AT_LEAST_ONE_FAILED`` (error branch fires when an
      upstream failed; other upstreams may have succeeded).
    - All ``Succeeded`` / ``None`` → ``None`` (DAB default ``ALL_SUCCESS``).

    Args:
        outcomes: The ADF dependency-condition strings from each edge.

    Returns:
        A DAB ``run_if`` enum string, or ``None`` to keep the default.
    """
    normalised = [outcome for outcome in outcomes if outcome]
    if not normalised:
        return None
    if any(outcome in ("Completed", "Skipped") for outcome in normalised):
        return "ALL_DONE"
    if any(outcome == "Failed" for outcome in normalised):
        return "AT_LEAST_ONE_FAILED"
    return None


def _build_common_task_fields(activity: Activity) -> dict[str, Any]:
    """Build the common task-level fields shared by all task types.

    Args:
        activity: Any IR activity node.

    Returns:
        A dict with ``task_key``, ``depends_on``, ``timeout_seconds``, and
        retry fields populated from the activity.
    """
    task: dict[str, Any] = {"task_key": activity.task_key}

    if activity.depends_on:
        task["depends_on"] = [{"task_key": dep.task_key} for dep in activity.depends_on]
        run_if = _run_if_from_adf_outcomes([dep.outcome for dep in activity.depends_on])
        if run_if:
            task["run_if"] = run_if

    if activity.timeout_seconds is not None and activity.timeout_seconds > 0:
        task["timeout_seconds"] = activity.timeout_seconds

    if activity.max_retries is not None and activity.max_retries > 0:
        task["retry_on_timeout"] = True
        task["max_retries"] = activity.max_retries
        if activity.min_retry_interval_millis is not None:
            task["min_retry_interval_millis"] = activity.min_retry_interval_millis

    if activity.description:
        task["description"] = activity.description

    return task


def prepare_activity(
    activity: Activity,
    *,
    scope: str = "",
    variable_task_keys: dict[str, str] | None = None,
) -> PreparedActivity:
    """Dispatch to the appropriate activity preparer based on type.

    Args:
        activity: An IR activity node of any concrete type.
        scope: Secret scope name (typically the pipeline/job name).  Passed
            through to activity preparers that create secret instructions.

    Returns:
        A PreparedActivity with the task dict and any associated artifacts.

    Raises:
        ValueError: If the activity type has no registered preparer.
    """
    # Import activity preparers lazily to avoid circular imports
    from orchestra.preparer.activity_preparers import (
        append_variable,
        copy,
        databricks_job,
        delete,
        execute_pipeline,
        filter,
        for_each,
        if_condition,
        lookup,
        notebook,
        set_variable,
        spark_jar,
        spark_python,
        switch,
        wait,
        web_activity,
    )

    dispatch: dict[type, Any] = {
        NotebookActivity: notebook.prepare,
        SparkJarActivity: spark_jar.prepare,
        SparkPythonActivity: spark_python.prepare,
        CopyActivity: copy.prepare,
        LookupActivity: lookup.prepare,
        WebActivity: web_activity.prepare,
        DeleteActivity: delete.prepare,
        SetVariableActivity: set_variable.prepare,
        FilterActivity: filter.prepare,
        AppendVariableActivity: append_variable.prepare,
        ForEachActivity: for_each.prepare,
        IfConditionActivity: if_condition.prepare,
        ExecutePipelineActivity: execute_pipeline.prepare,
        RunJobActivity: databricks_job.prepare,
        SwitchActivity: switch.prepare,
        WaitActivity: wait.prepare,
    }

    preparer_fn = dispatch.get(type(activity))

    # Handle placeholder and unsupported activities with a generic notebook
    if preparer_fn is None:
        if isinstance(activity, (PlaceholderActivity, UnsupportedActivity)):
            return _prepare_placeholder(activity)
        raise ValueError(
            f"No preparer registered for activity type {type(activity).__name__} (task_key={activity.task_key!r})"
        )

    # Pass variable_task_keys to preparers that need the most-recent-writer
    # of each pipeline variable — NotebookActivity reads it to rewrite
    # @variables() references, and AppendVariableActivity reads it to find
    # the prior value to append to.
    if type(activity) is NotebookActivity:
        return preparer_fn(activity, scope=scope, variable_task_keys=variable_task_keys)
    if type(activity) is AppendVariableActivity:
        return preparer_fn(activity, scope=scope, variable_task_keys=variable_task_keys)
    return preparer_fn(activity, scope=scope)


def _prepare_placeholder(activity: Activity) -> PreparedActivity:
    """Create a placeholder notebook task for unsupported or agentic activities.

    Args:
        activity: A PlaceholderActivity or UnsupportedActivity.

    Returns:
        A PreparedActivity with a stub notebook.
    """
    task = _build_common_task_fields(activity)

    if isinstance(activity, PlaceholderActivity):
        comment = activity.comment or "This activity requires manual implementation."
        original_type = activity.original_type
    elif isinstance(activity, UnsupportedActivity):
        comment = activity.reason or "This activity type is not supported."
        original_type = activity.original_type
    else:
        comment = "Unknown activity type."
        original_type = type(activity).__name__

    notebook_name = f"{activity.task_key}.py"
    notebook_path = f"notebooks/{notebook_name}"

    content = (
        "# Databricks notebook source\n"
        "# MAGIC %md\n"
        f"# MAGIC # Placeholder: {activity.name}\n"
        "# MAGIC\n"
        f"# MAGIC Original ADF activity type: **{original_type}**\n"
        "# MAGIC\n"
        f"# MAGIC {comment}\n"
        "\n# COMMAND ----------\n\n"
        f"raise NotImplementedError(\"Activity '{activity.name}' ({original_type}) requires manual implementation.\")\n"
    )

    task["notebook_task"] = {
        "notebook_path": f"../src/{notebook_path}",
    }

    notebook = DabNotebook(
        relative_path=notebook_path,
        content=content,
    )

    return PreparedActivity(task=task, notebooks=[notebook])


def merge_prepared_aggregates(
    prepared: PreparedActivity,
    *,
    notebooks: list[DabNotebook],
    secrets: list[SecretInstruction],
    setup_tasks: list[SetupTask],
    inner_workflows: list[PreparedWorkflow],
) -> None:
    """Append a :class:`PreparedActivity`'s aggregate fields into shared lists.

    Every preparer that fans an activity out into child sub-prepares
    (``prepare_workflow`` itself, ``IfCondition`` branches, ``Switch``
    cases) needs to merge the same four collections back up into the
    outer scope.  Centralising the merge here keeps the call sites short
    and makes adding a new aggregate field a single-edit change.

    Mutates the four lists in place; ``prepared.task`` and
    ``prepared.extra_tasks`` are intentionally left to the caller because
    different scopes wire them up differently (top-level tasks, branch
    bodies, ForEach inner tasks, ...).
    """
    notebooks.extend(prepared.notebooks)
    secrets.extend(prepared.secrets)
    setup_tasks.extend(prepared.setup_tasks)
    inner_workflows.extend(prepared.inner_workflows)


def prepare_workflow(pipeline: Pipeline) -> PreparedWorkflow:
    """Convert a Pipeline IR into a PreparedWorkflow.

    Iterates over all tasks in the pipeline, dispatches each to the
    appropriate activity preparer, and aggregates the results into a
    single PreparedWorkflow containing all task dicts, notebooks,
    secrets, and setup tasks.

    Args:
        pipeline: The translated Pipeline IR to prepare.

    Returns:
        A PreparedWorkflow ready for the DAB bundle writer.
    """
    all_tasks: list[dict[str, Any]] = []
    all_notebooks: list[DabNotebook] = []
    all_secrets: list[SecretInstruction] = []
    all_setup_tasks: list[SetupTask] = []
    all_inner_workflows: list[PreparedWorkflow] = []
    cluster_hints: list[dict[str, Any]] = []
    task_key_remap: dict[str, str] = {}

    scope = pipeline.name

    # Build variable-name → task-key mapping so downstream preparers can
    # resolve @variables('name') / find the most-recent writer to append to.
    # The map is updated in pipeline-declaration order so AppendVariable
    # sees the last SetVariable/AppendVariable that preceded it.
    variable_task_keys_map: dict[str, str] = {}

    for activity in pipeline.tasks:
        prepared = prepare_activity(activity, scope=scope, variable_task_keys=variable_task_keys_map)
        all_tasks.append(prepared.task)
        all_tasks.extend(prepared.extra_tasks)
        merge_prepared_aggregates(
            prepared,
            notebooks=all_notebooks,
            secrets=all_secrets,
            setup_tasks=all_setup_tasks,
            inner_workflows=all_inner_workflows,
        )
        task_key_remap.update(prepared.task_key_remap)
        if activity.cluster:
            cluster_hints.append(dict(activity.cluster))

        if isinstance(activity, (SetVariableActivity, AppendVariableActivity)):
            variable_task_keys_map[activity.variable_name] = activity.task_key

    # Apply any task-key renames (today only Switch uses this, to push the
    # first case from <activity> to <activity>__case_<value>).  Walk every
    # task and rewrite ``depends_on[].task_key`` references that match a
    # remap entry — preserves edges from activities that referenced the
    # logical pre-rename name.
    if task_key_remap:
        for task in all_tasks:
            for dep in task.get("depends_on", []) or []:
                old = dep.get("task_key")
                if old in task_key_remap:
                    dep["task_key"] = task_key_remap[old]

    # Deduplicate secrets by (scope, key)
    seen_secrets: set[tuple[str, str]] = set()
    unique_secrets: list[SecretInstruction] = []
    for secret in all_secrets:
        secret_id = (secret.scope, secret.key)
        if secret_id not in seen_secrets:
            seen_secrets.add(secret_id)
            unique_secrets.append(secret)

    return PreparedWorkflow(
        name=pipeline.name,
        tasks=all_tasks,
        notebooks=all_notebooks,
        secrets=unique_secrets,
        setup_tasks=all_setup_tasks,
        inner_workflows=all_inner_workflows,
        cluster_hints=cluster_hints,
    )
